app/common/views.py
#
# Author: Andrew Watts <awatts2@ur.rochester.edu>
#
# Copyright (c) 2014-2016, Andrew Watts and the University of Rochester BCS Department
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

from __future__ import print_function
from __future__ import absolute_import
import os
# import time
from flask import Blueprint, request, render_template, redirect, abort, url_for
from flask_admin.contrib.sqla import ModelView
import flask_login as login
from flask_security import login_required
from werkzeug.exceptions import BadRequest
from sqlalchemy.orm.exc import NoResultFound
from itsdangerous import URLSafeSerializer, BadSignature
from app.models import Experiment, TrialList, NotificationEvent, Protocol, User, Role
from app import app, db, admin

mod = Blueprint('common',
                __name__,
                template_folder='templates',
                static_folder='static',
                static_url_path='/static/common')

# we want the 'app' directory to be the base
basepath = os.path.split(os.path.dirname(__file__))[0]


@app.errorhandler(400)
def bad_request(error):
    return render_template('400.html', error=error), 400


@app.route('/')
def app_root():
    return render_template('home.jinja2')


@mod.route('/experiments')
@login_required
def experiments():
    return render_template('experiments.jinja2', experiments=Experiment.query.all())


@mod.route('/experiments/<experiment>')
@login_required
def experiment_detail(experiment):
    try:
        e = Experiment.query.filter_by(name=experiment).one()
        return render_template('experiment_detail.jinja2', experiment=e)
    except NoResultFound:
        abort(400, {'message': 'No such experiment as {}'.format(experiment)})


#  http://stackoverflow.com/a/13318415/3846301
def has_no_empty_params(rule):
    defaults = rule.defaults if rule.defaults is not None else ()
    arguments = rule.arguments if rule.arguments is not None else ()
    return len(defaults) >= len(arguments)


@mod.route('/site-map')
@login_required
def site_map():
    links = []
    for rule in app.url_map.iter_rules():
        # Filter out rules we can't navigate to in a browser
        # and rules that require parameters
        if "GET" in rule.methods and has_no_empty_params(rule):
            url = url_for(rule.endpoint)
            links.append((url, rule.endpoint))
            # links is now a list of url, endpoint tuples
    return render_template("all_links.jinja2", links=links)


@mod.route('/echo/', methods=['POST'])
def response_repeater():
    """
    Take all the keys and values in a request object and print them in a table
    """
    return render_template('echo.jinja2', formdata=request.form)


@app.context_processor
def utility_processor() -> dict:
    return dict(get_upload_link=get_upload_link)


# Some parts based on http://flask.pocoo.org/snippets/50/
def get_serializer(secret_key=None):
    if secret_key is None:
        secret_key = app.secret_key
    return URLSafeSerializer(secret_key)


def get_upload_link(experiment, workerid, assignmentid, trial):
    s = get_serializer()
    payload = s.dumps((experiment, workerid, assignmentid, trial))
    return url_for('common.wav_uploader', payload=payload, _external=True)


@mod.route('/wav_uploader/<payload>', methods=['PUT', ])
def wav_uploader(payload):
    """
    Handle WAV uploads
    """
    # TODO: should only allow XHR
    # print(request.headers)
    s = get_serializer()
    try:
        experiment, workerid, assignmentid, trial = s.loads(payload)
        print('{},{},{}'.format(workerid, assignmentid, trial))
    except BadSignature:
        print('bad signature')
        raise BadRequest('Invalid file signature')

    if request.content_type != 'audio/x-wav':
        print('need wavs')
        raise BadRequest('Only WAV files can be uploaded')

    savepath = os.path.join(basepath, 'uploads', experiment, workerid, assignmentid)
    savefile = trial + ".wav"

    if not os.path.exists(savepath):
        os.makedirs(savepath)

    with open(os.path.join(savepath, savefile), 'wb') as wavfile:
        wavfile.write(request.data)

    return 'Uploaded "{}"'.format(savefile)


class AuthorizedModelView(ModelView):
    def is_accessible(self):
        return login.current_user.has_role('admin') or login.current_user.has_role('editor')

    def inaccessible_callback(self, name, **kwargs):
        # redirect to login page if user doesn't have access
        return redirect(url_for('security.login', next=request.url))


class NotificationView(AuthorizedModelView):
    can_create = False
    can_edit = False
    can_delete = False
    column_filters = ['event_type', 'event_time']


class UserView(AuthorizedModelView):
    column_exclude_list = ('password', )
    column_hide_backrefs = False
    column_list = ('email', 'active', 'confirmed', 'roles')


admin.add_view(AuthorizedModelView(Protocol, db.session))
admin.add_view(AuthorizedModelView(Experiment, db.session))
admin.add_view(AuthorizedModelView(TrialList, db.session))
admin.add_view(NotificationView(NotificationEvent, db.session))
admin.add_view(UserView(User, db.session))
admin.add_view(AuthorizedModelView(Role, db.session))

app/sprrunner/views.py
#
# Author: Andrew Watts <awatts2@ur.rochester.edu>
#
# Copyright (c) 2014-2016, Andrew Watts and the University of Rochester BCS Department
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

from __future__ import print_function
from __future__ import absolute_import

from functools import partial
import os.path
from six.moves import configparser
from six.moves.configparser import NoSectionError, NoOptionError
from flask import Blueprint, render_template, request, abort
from jinja2.exceptions import TemplateNotFound

try:
    from config import GMAPS_API_KEY
except ImportError:
    GMAPS_API_KEY = 'key_import_failed'
from app.utils import get_or_create_worker_assignment, random_list, static_list

basepath = os.path.dirname(__file__)

mod = Blueprint('sprrunner',
                __name__,
                url_prefix='/sprrunner',
                template_folder='templates',
                static_folder='static',
                static_url_path='/static/sprrunner')


@mod.route('/')
def web_spr_server():
    """
    WSGI compatible class to dispatch pages for the experiment
    """

    condition = None
    required_keys = {'assignmentId', 'hitId', 'experiment'}
    key_error_msg = 'Missing parameter: {0}. Required keys: {1}'

    # if 'debug' in request.args:
    #     app.debug = request.args['debug'] == '1'
    # forcelist = None
    # if 'list' in request.args:
    #     forcelist = request.args['list']

    missing_keys = set()
    for k in required_keys:
        if k not in request.args:
            missing_keys.add(k)
    if missing_keys:
        abort(400, {'message': key_error_msg.format(missing_keys, required_keys)})

    cfg = configparser.ConfigParser()
    config_expt = request.args['experiment']
    if 'region' in request.args:
        config_expt += '-{}'.format(request.args['region'])
    cfg_file = cfg.read(os.path.join(basepath, 'experiment_config', '{}.cfg'.format(config_expt)))
    if not cfg_file:
        abort(400, dict(message='{}.cfg does not exist'.format(config_expt)))
    try:
        listtype = cfg.get('lists', 'type')
    except (NoSectionError, NoOptionError) as e:
        abort(400, {'message': 'In {}: {}'.format(cfg_file, e.message)})

    if listtype == 'filtered':
        lsubset = cfg.get('lists', 'lists').strip().split(',')
    elif listtype == 'static':
        lname = cfg.get('lists', 'list')

    template_file = 'webspr.jinja2'
    if cfg.has_section('template'):
        template_file = cfg.get('template', 'override')
    # print(template_file)

    if 'region' in request.args:
        try:
            states = {
                'names': cfg.get('states', 'names').strip().split(','),
                'abbrevs': cfg.get('states', 'abbrevs').strip().split(',')
            }
        except (NoSectionError, NoOptionError) as e:
            abort(400, {'message': 'In {}: {}'.format(cfg_file, e.message)})
    else:
        states = {'names': [], 'abbrevs': []}

    in_preview = request.args['assignmentId'] == 'ASSIGNMENT_ID_NOT_AVAILABLE'

    formtype = None
    if 'dest' in request.args:
        if request.args['dest'] in ('mturk', 'sandbox'):
            formtype = request.args['dest']
        else:
            abort(400, {'message': "{} is not a valid form destination".format(request.args['dest'])})

    # print('Debug: {}, Forcelist: {}'.format(debug, forcelist))

    assignment = None
    if not in_preview:
        if 'workerId' not in request.args:
            missing_keys.add('workerId')
            required_keys.add('workerId')
            abort(400, {'message': key_error_msg.format(missing_keys, required_keys)})
        get_assignment = partial(get_or_create_worker_assignment,
                                 request.args['experiment'],
                                 request.args['workerId'],
                                 request.args['assignmentId'])
        if listtype == 'random':
            assignment = get_assignment('random')
        elif listtype == 'filtered':
            assignment = get_assignment('filtered', lsubset=lsubset)
        elif listtype == 'static':
            assignment = get_assignment('static', listname=lname)

    if assignment:
        condition = "{}/{}".format(request.args['experiment'], assignment.triallist.name)
    # FIXME: Whatever the hell I was doing here, figure out how to do it right with Flask
    #     if app.debug and forcelist:
    #         formtype = 'testing'  # should never need to debug on live
    #         listname = forcelist
    #         try:
    #             condref = TrialList.query.filter_by(experiment=request.args['experiment'], name=listname).one()
    #         except:
    #             abort(400, {'message': "Could not find list {} for {}".format(listname, request.args['experiment'])})
    #         condition = condref.name
    #     else:
    #         condition = worker.triallist.name

    # if (worker is not None and worker.completed):
    #     render_template('sorry.html')
    # else:
    try:
        return render_template(template_file,
                               amz=request.args,
                               experiment=request.args['experiment'],
                               condition=condition,
                               formtype=formtype,
                               # debug=1 if app.debug else 0,
                               jqueryui=1,  # FIXME: this should be set programmatically
                               gmaps_key=GMAPS_API_KEY,  # FIXME: this isn't always necessary
                               states=states,
                               # on preview, don't bother loading heavy flash assets
                               preview=in_preview)
    except TemplateNotFound as e:
        abort(400, {'message': '{}'.format(e.message)})


@mod.route('/demo/<experiment>')
@mod.route('/demo/<experiment>/<int:listid>')
@mod.route('/demo/<experiment>/<region>')
@mod.route('/demo/<experiment>/<region>/<listname>')
def spr_demo(experiment, region=None, listname=None, listid=None):
    amz = {
        'experiment': experiment,
        'assignmentId': 'NA',
        'region': region
    }

    cfg = configparser.ConfigParser()
    config_expt = experiment
    if region:
        config_expt += '-{}'.format(region)
    cfg_file = cfg.read(os.path.join(basepath, 'experiment_config', '{}.cfg'.format(config_expt)))
    if not cfg_file:
        abort(400, dict(message='{}.cfg does not exist'.format(config_expt)))

    template_file = 'webspr.jinja2'
    if cfg.has_section('template'):
        template_file = cfg.get('template', 'override')
    # print(template_file)

    if region:
        try:
            states = {
                'names': cfg.get('states', 'names').strip().split(','),
                'abbrevs': cfg.get('states', 'abbrevs').strip().split(',')
            }
        except (NoSectionError, NoOptionError) as e:
            abort(400, {'message': 'In {}: {}'.format(cfg_file, e.message)})
    else:
        states = {'names': [], 'abbrevs': []}

    if listname:
        triallist = static_list(experiment, listname)
    elif listid:
        triallist = static_list(experiment, listid)
    else:
        triallist = random_list(experiment)
    condition = "{}/{}".format(experiment, triallist.name)

    try:
        return render_template(template_file,
                               amz=amz,
                               experiment=experiment,
                               condition=condition,
                               formtype='local',
                               # debug=1 if app.debug else 0,
                               jqueryui=1,  # FIXME: this should be set programmatically
                               gmaps_key=GMAPS_API_KEY,  # FIXME: this isn't always necessary
                               states=states,
                               # on preview, don't bother loading heavy flash assets
                               preview=False)
    except TemplateNotFound as e:
        abort(400, {'message': '{}'.format(e.message)})

app/common/templates/all_links.jinja2
{% extends "base.jinja2" %}
{% block title %}All Links{% endblock %}

{% block content %}
    <ul>
    {% for url, endpoint in links %}
        <li><a href="{{ url }}">{{ endpoint }}</a></li>
    {% endfor %}
    </ul>
{% endblock %}

app/common/templates/base.jinja2
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="utf-8" />
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {% block extracss %}{% endblock %}
    </head>

    <body>
        {% block content %}{% endblock %}

        {% block form %}{% endblock %}

        {% block extrajs %}{% endblock %}
    </body>
</html>

app/common/templates/echo.jinja2
{% extends "base.jinja2" %}
{% block title %}Form data{% endblock %}
{% block extracss %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.29.0/css/theme.default.min.css" integrity="sha256-kZJ4kB78IbXuxMtCpmaXzii8vxEKtu8pjicH62E0/qM=" crossorigin="anonymous" />
{% endblock %}

{% block content %}
    <table id="formdata">
        <thead>
            <tr><td>Key</td><td>Value</td></tr>
        </thead>
        <tbody>
            {% for k,v in formdata.items() %}
            <tr><td>{{k}}</td><td>{{v}}</td></tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block extrajs %}
    <!--[if lt IE 9]>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <![endif]-->
    <!--[if gte IE 9]><!-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <!--<![endif]-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.29.0/js/jquery.tablesorter.min.js" integrity="sha256-UD/M/6ixbHIPJ/hTwhb9IXbHG2nZSiB97b4BSSAVm6o=" crossorigin="anonymous"></script>
    <script type="text/javascript">
        $(document).ready(function() { $("#formdata").tablesorter({initWidgets: true, widgets: ['zebra']}); });
    </script>
{% endblock %}

app/common/templates/experiment_base.jinja2
{% extends "base.jinja2" %}
{% block extracss %}
    {% if jqueryui %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/redmond/jquery-ui.min.css" integrity="sha256-pXjw+x4dOoTZgRBmPD/ilEFccRj2c57rZaYj9A9kRrQ=" crossorigin="anonymous" />
    {% endif %}
    <style type="text/css">
        #comment, #submit {display:none;}
    </style>
    {% block exptcss %}{% endblock %}
    {% block headjs %}{% endblock %}
{% endblock %}

{% block form %}
{% if formtype == 'sandbox' %}
    <form id="results" method="post" action="https://workersandbox.mturk.com/mturk/externalSubmit">
{% elif formtype == 'mturk' %}
    <form id="results" method="post" action="https://www.mturk.com/mturk/externalSubmit">
{% else %}
    <form id="results" method="post" action="{{ url_for('common.response_repeater') }}">
{% endif %}
{% block formfields %}{% endblock %}
{% block exptformfields %}{% endblock %}
<input type="hidden" id="experiment" name="experiment" value="{{experiment}}"/>
<input type="hidden" id="list" name="list" value="{{condition}}"/>
<input type="hidden" id="assignmentId" name="assignmentId" value="{{amz.assignmentId}}"/>
<input type="hidden" id="browserid" name="browserid" value="NA"/>
<div id="comment">
    <p>If you are interested in hearing how the experiments you are
        participating in help us to understand the human brain, feel
        free to subscribe to our <a href="https://hlplab.wordpress.com/">
            lab blog</a> on which we announce new findings. Note that
        typically about one year passes before an experiment is
        published.</p>
    <p>Feedback on this HIT (optional):</p>
    <p><textarea id="commentarea" name="comment" cols="80" rows="3"></textarea></p>
</div>
<button type="submit" name="submit" id="submit" disabled="disabled">Submit</button>
</form>
<!--[if lt IE 9]>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<![endif]-->
<!--[if gte IE 9]><!-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
<!--<![endif]-->
{% if formtype == 'live' %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-migrate/3.0.0/jquery-migrate.min.js" integrity="sha256-JklDYODbg0X+8sPiKkcFURb5z7RvlNMIaE3RA2z97vw=" crossorigin="anonymous"></script>
{% else %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-migrate/3.0.0/jquery-migrate.js" integrity="sha256-aMjiiYtQDaPPLj8A9EwJjh8dzP6iyo9pgcSjLaIYTnc=" crossorigin="anonymous"></script>
{% endif %}
{% endblock %}

{% block extrajs %}
{% if jqueryui %}
    <script type="text/javascript">$.uiBackCompat = false;</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" integrity="sha256-KM512VNnjElC30ehFwehXjx1YCHPiQkOPmqnrWtpccM=" crossorigin="anonymous"></script>
{% endif %}
{% block exptjs %}{% endblock %}
{% endblock %}

app/common/templates/experiment_detail.jinja2
{% extends "base.jinja2" %}
{% block title %}{{experiment.name}}{% endblock %}
{% block extracss %}<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.19.1/css/theme.default.css"/>{% endblock %}

{% block content %}
    <h1>{{experiment.name}}</h1>

    <h2>Lists</h2>
    <table id="lists" class="tablesorter">
        <thead>
            <tr><td>Number</td><td>Name</td><td>Assignments</td></tr>
        </thead>
        <tbody>
    {% for l in experiment.lists %}
        <tr><td>{{l.number}}</td><td>{{l.name}}<td>{{l.assignments|count}}</td></tr>
    {% endfor %}
        </tbody>
    </table>

    <h2>Assignments</h2>
    <table id="assignments" class="tablesorter">
    <thead>
      <tr><td>AssignmentId</td><td>State</td><td>List</td></tr>
    </thead>
    {% for a in experiment.assignments %}
    <tr><td>{{a.assignmentid}}</td><td>{{a.state}}</td><td>{{a.triallist.name}}</td></tr>
    {% endfor %}
    </table>
{% endblock %}

{% block extrajs %}
    <!--[if lt IE 9]>
        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <![endif]-->
    <!--[if gte IE 9]><!-->
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.19.1/js/jquery.tablesorter.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $("#lists").tablesorter();
            $("#assignments").tablesorter();
        });
    </script>
    <!--<![endif]-->
{% endblock %}

app/common/templates/experiments.jinja2
{% extends "base.jinja2" %}
{% block title %}Available experiments{% endblock %}
{% block content %}
    <div id="experiments">
        <h2>Experiments</h2>
        <p>Total: {{experiments|length}} experiments</p>
        <ul>{% for e in experiments %}
            <li>
                <a href="{{ url_for('common.experiment_detail', experiment=e.name)}}">{{e.name}}</a>
                <a href="{{ url_for('sprrunner.spr_demo', experiment=e.name) }}">(demo - random)</a>
                <ul class="inline-list">
                {% for lst in e.lists %}
                <li><a href="{{ url_for('sprrunner.spr_demo', experiment=e.name, listid=lst.id) }}">(demo - {{lst.name}})</a></li>
                {% endfor %}
                </ul>
            </li>
        {% endfor %}
        </ul>
    </div>
{% endblock %}

app/common/templates/home.jinja2
{% extends "base.jinja2" %}
{% block title %}Application Home{% endblock %}
{% block content %}
<p>Hi There!</p>
<p>There's no content at the root</p>
{% endblock %}

app/common/templates/oldbrowser.jinja2
<div id="oldBrowserMessage">
    <p>Your browser does not appear to be compatible with the some HTML5 and JavaScript features used in this HIT.</p>
    <p>Please <strong>do not accept this HIT</strong>, your results will be automatically rejected.  </p>
    <p>If you'd like to do this HIT, download an up-to-date version of one of these browsers and try again:</p>
    <div id="browserIcons">
      <a target="_blank" href="http://www.google.com/chrome"><img src="{{ url_for('common.static', filename='img/64-chrome.png') }}" alt="Google Chrome" width="71" height="66" /></a>
      <a target="_blank" href="http://www.mozilla.com/en-US/firefox/new/"><img src="{{ url_for('common.static', filename='img/64-firefox.png') }}" alt="Mozilla Firefox" width="71" height="66" /></a>
      <a target="_blank" href="http://www.opera.com/"><img src="{{ url_for('common.static', filename='img/64-opera.png') }}" alt="Opera" width="71" height="66" /></a>
      <a target="_blank" href="https://www.microsoft.com/en-us/windows/microsoft-edge"><img src="{{ url_for('common.static', filename='img/edge.png') }}" alt="Microsoft Edge" width="61" height="66"/></a>
      <a target="_blank" href="http://www.apple.com/safari/"><img src="{{ url_for('common.static', filename='img/64-safari.png') }}" alt="Safari" width="71" height="66"/></a>
    </div>
</div>

app/common/templates/sorry.html
<!DOCTYPE html>
<html>
    <head>
        <title>WebSPR</title>
        <meta charset="UTF-8"/>
    </head>
    <body>
        <p>Sorry. You did a previous version of this experiment and you cannot do it again. Please return this HIT.</p>
    </body>
</html>

app/common/templates/state_select.html
<div id="current_state">
    <p>What state are you currently in?</p>
    <select name="reported_state">
        <option selected value="NA">------</option>
        <option value="AL">Alabama</option>
        <option value="AK">Alaska</option>
        <option value="AZ">Arizona</option>
        <option value="AR">Arkansas</option>
        <option value="CA">California</option>
        <option value="CO">Colorado</option>
        <option value="CT">Connecticut</option>
        <option value="DE">Delaware</option>
        <option value="DC">District of Columbia</option>
        <option value="FL">Florida</option>
        <option value="GA">Georgia</option>
        <option value="HI">Hawaii</option>
        <option value="ID">Idaho</option>
        <option value="IL">Illinois</option>
        <option value="IN">Indiana</option>
        <option value="IA">Iowa</option>
        <option value="KS">Kansas</option>
        <option value="KY">Kentucky</option>
        <option value="LA">Louisiana</option>
        <option value="ME">Maine</option>
        <option value="MD">Maryland</option>
        <option value="MA">Massachusetts</option>
        <option value="MI">Michigan</option>
        <option value="MN">Minnesota</option>
        <option value="MS">Mississippi</option>
        <option value="MO">Missouri</option>
        <option value="MT">Montana</option>
        <option value="NE">Nebraska</option>
        <option value="NV">Nevada</option>
        <option value="NH">New Hampshire</option>
        <option value="NJ">New Jersey</option>
        <option value="NM">New Mexico</option>
        <option value="NY">New York</option>
        <option value="NC">North Carolina</option>
        <option value="ND">North Dakota</option>
        <option value="OH">Ohio</option>
        <option value="OK">Oklahoma</option>
        <option value="OR">Oregon</option>
        <option value="PA">Pennsylvania</option>
        <option value="RI">Rhode Island</option>
        <option value="SC">South Carolina</option>
        <option value="SD">South Dakota</option>
        <option value="TN">Tennessee</option>
        <option value="TX">Texas</option>
        <option value="UT">Utah</option>
        <option value="VT">Vermont</option>
        <option value="VA">Virginia</option>
        <option value="WA">Washington</option>
        <option value="WV">West Virginia</option>
        <option value="WI">Wisconsin</option>
        <option value="WY">Wyoming</option>
    </select>
    <button type="button" id="gogeolocate" disabled="disabled">Continue to geolocation</button>
</div>